### PR TITLE
Create VisCap.cfg

### PR DESCRIPTION
**Pull request by arnavaz**

### CODE REVIEW

**Comment by biocyberman** [comment]
@arnavaz I looked through the VisCap.R in the upstream and in your fork, I did not find anywhere VisCap make use of this file. Can you give some more information?  I am trying to setup VisCap to run in Linux.

From the current source code (line 545 - 551) the command for Linux (running uninteractive):

`Rscript VisCap.R lane_dir out_dir interval_list_dir`

Thanks

**Comment by arnavaz** [comment]
Hi!
To run VisCap on a linux machine you can run it on command line by using:

Rscript  VisCap.R  VisCap.cfg cancer_sample_dir output_dir

You need to set up your VisCap.cfg file in advance of this. 

Hope this helps,
Arnavaz

**Comment by tjpugh** [comment]
Do you mean VisCapCancer, Arna? I think we should post that code publicly as well. Jeff, can you help with that?
- Trevor

On Wed, Oct 5, 2016 at 5:20 PM -0400, "arnavaz" <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi!
To run VisCap on a linux machine you can run it on command line by using:

Rscript VisCap.R VisCap.cfg cancer_sample_dir output_dir

You need to set up your VisCap.cfg file in advance of this.

Hope this helps,
Arnavaz

**Comment by tjpugh** [comment]
We do have a viscap cancer bitbucket repositorty:
https://bitbucket.org/pughlab/viscapcancer, Should we just make something
one public?  Probably best not to have too many versions floating around.

**Comment by biocyberman** [comment]
@arnavaz I went through the source of VisCap.R quite thoroughly, I am pretty sure VisCap.R does not know how to use VisCap.cfg. I managed to run VisCap.R on Linux anyway. I also made some improvement on the file. I can submit pull request later.

@tjpugh I am interested in the viscapcancer too :)

**Comment by svsgvarma** [comment]
Hi, 

I have configured the VisCap.cfg file by changing 4 fields as below. 

panel.of.normals              <- FALSE
custom_gridlines_file         <- "~/cytoBandIdeo_hg19.txt" # file path for cytoBand info from ucsc
interval_list_dir             <- "~/My_DOC_Dir/" # The directory that contains the interval file
interval_file_pattern         <- "^ExomeTargets-20130108-hg19_pars.bed$" # interval filename

However, while compiling on command line in linux, I have an error as below, any clue why this occurs?

####################

$Rscript VisCap.R VisCap.cfg ~/My_DOC_Dir/ ~/out_viscap/

Attaching package: ‘gplots’
The following object is masked from ‘package:stats’:
    lowess
Attaching package: ‘zoo’
The following objects are masked from ‘package:base’:
    as.Date, as.Date.numeric
character(0)
Error in make_matrix_from_cov_files(lane_dir, cov_file_pattern, cov_field) : 
  object 'mat.cov' not found
Execution halted

####################

/G Varma

**Comment by tjpugh** [comment]
It looks like VisCap can’t find your coverage files, possibly due to an incorrectly set cov_file_pattern or cov_field variants in the cfg files. Can you provide an example file name for your Depth of Coverage files and your settings for those two variables?
- Trevor

**Comment by svsgvarma** [comment]
I checked by providing different pattern and full name even then I got the same error!

###---- names of my Depth of Coverage files 

$~/My_DOC_Dir$ ls
ExomeTargets-20130108-hg19_pars_nochr.bed
Genes_refgene_nochr_1-22_sortg35_rm-ctg-gl00.txt
W3_DepthOfCoverage.depth
W3_DepthOfCoverage.depth.sample_cumulative_coverage_counts
W3_DepthOfCoverage.depth.sample_cumulative_coverage_proportions
W3_DepthOfCoverage.depth.sample_gene_summary
W3_DepthOfCoverage.depth.sample_gene_summary_all-mean_cvg
W3_DepthOfCoverage.depth.sample_interval_statistics
W3_DepthOfCoverage.depth.sample_interval_summary
W3_DepthOfCoverage.depth.sample_statistics
W3_DepthOfCoverage.depth.sample_summary

###---settings for those two variables
cov_file_pattern              <- ".sample_interval_summary$" # Keep this as default when you are using DepthOfCoverage files from Gatk
cov_field                     <- "_total_cvg" # Keep as default

/GVarma

**Pull request merged**
